#ifndef QPROPERTYMODEL_GLOBAL_H
#define QPROPERTYMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef QPROPERTYMODEL_LIBRARY
# define QPROPERTYMODEL_EXPORT Q_DECL_EXPORT
#else
# define QPROPERTYMODEL_EXPORT Q_DECL_IMPORT
#endif

#endif // QPROPERTYMODEL_GLOBAL_H
